
export const LOAD_EDUCATION_HISTORY_DATA = "LOAD_EDUCATION_HISTORY_DATA";
export const LOAD_ACADEMIC_PROJECTS_DATA = "LOAD_ACADEMIC_PROJECTS_DATA";
export const LOAD_PERSONAL_PROJECTS_DATA = "LOAD_PERSONAL_PROJECTS_DATA";
export const LOAD_ABOUT_DATA = "LOAD_ABOUT_DATA";
export const ERROR_LOADING_DATA = 'ERROR_LOADING_DATA';


