/**
 * Author: Victor Trejo.
 * Description: This file contains all the Action types constants that can
 *              be dispatched.
 */
export default Object.freeze({
  LOAD_EDUCATION_HISTORY_DATA: 'LOAD_EDUCATION_HISTORY_DATA',
  LOAD_EXPERIENCE_HISTORY_DATA: 'LOAD_EXPERIENCE_HISTORY_DATA',
  LOAD_ACADEMIC_PROJECTS_DATA: 'LOAD_ACADEMIC_PROJECTS_DATA',
  LOAD_PERSONAL_PROJECTS_DATA: 'LOAD_PERSONAL_PROJECTS_DATA',
  LOAD_ABOUT_DATA: 'LOAD_ABOUT_DATA',
  LOAD_JUMBOTRON_DATA: 'LOAD_JUMBOTRON_DATA',
  LOAD_RESUME_DATA: 'LOAD_RESUME_DATA',
  LOAD_PROFILE_PICTURE_DATA: 'LOAD_PROFILE_PICTURE_DATA',
  LOAD_SKILLS_DATA: 'LOAD_SKILLS_DATA',
  ERROR_LOADING_DATA: 'ERROR_LOADING_DATA',
});
